kind = "web"
previewPath = "/"
title = "IEEE Kerala ATIIG Website"
version = "1.0.0"
id = "artifacts/ieee-atiig"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22892

[services.development]
run = "pnpm --filter @workspace/ieee-atiig run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ieee-atiig", "run", "build" ]
publicDir = "artifacts/ieee-atiig/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22892"
BASE_PATH = "/"
